// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Acumatica.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ARQueryModified : Entity
    {
        /// <summary>
        /// Initializes a new instance of the ARQueryModified class.
        /// </summary>
        public ARQueryModified() { }

        /// <summary>
        /// Initializes a new instance of the ARQueryModified class.
        /// </summary>
        public ARQueryModified(Guid? id = default(Guid?), long? rowNumber = default(long?), string note = default(string), IDictionary<string, IDictionary<string, CustomField>> custom = default(IDictionary<string, IDictionary<string, CustomField>>), IList<FileLink> files = default(IList<FileLink>), StringValue docType = default(StringValue), StringValue referenceNbrARAdjustAdjdRefNbr = default(StringValue), StringValue adjgDocType = default(StringValue), StringValue adjgRefNbr = default(StringValue), IntValue adjustmentNbr = default(IntValue), DateTimeValue aRAdjustCreatedDateTime = default(DateTimeValue), DecimalValue aRAdjustCuryAdjdAmt = default(DecimalValue), DateTimeValue aRAdjustLastModifiedDateTime = default(DateTimeValue), DecimalValue balance = default(DecimalValue), DecimalValue amount = default(DecimalValue), StringValue type = default(StringValue), StringValue referenceNbrARRegisterRefNbr = default(StringValue), StringValue fromDate = default(StringValue), StringValue toDate = default(StringValue))
            : base(id, rowNumber, note, custom, files)
        {
            DocType = docType;
            ReferenceNbrARAdjustAdjdRefNbr = referenceNbrARAdjustAdjdRefNbr;
            AdjgDocType = adjgDocType;
            AdjgRefNbr = adjgRefNbr;
            AdjustmentNbr = adjustmentNbr;
            ARAdjustCreatedDateTime = aRAdjustCreatedDateTime;
            ARAdjustCuryAdjdAmt = aRAdjustCuryAdjdAmt;
            ARAdjustLastModifiedDateTime = aRAdjustLastModifiedDateTime;
            Balance = balance;
            Amount = amount;
            Type = type;
            ReferenceNbrARRegisterRefNbr = referenceNbrARRegisterRefNbr;
            FromDate = fromDate;
            ToDate = toDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DocType")]
        public StringValue DocType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReferenceNbrARAdjust_adjdRefNbr")]
        public StringValue ReferenceNbrARAdjustAdjdRefNbr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdjgDocType")]
        public StringValue AdjgDocType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdjgRefNbr")]
        public StringValue AdjgRefNbr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdjustmentNbr")]
        public IntValue AdjustmentNbr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ARAdjust_createdDateTime")]
        public DateTimeValue ARAdjustCreatedDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ARAdjust_curyAdjdAmt")]
        public DecimalValue ARAdjustCuryAdjdAmt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ARAdjust_lastModifiedDateTime")]
        public DateTimeValue ARAdjustLastModifiedDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Balance")]
        public DecimalValue Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public DecimalValue Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public StringValue Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReferenceNbrARRegister_refNbr")]
        public StringValue ReferenceNbrARRegisterRefNbr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromDate")]
        public StringValue FromDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ToDate")]
        public StringValue ToDate { get; set; }

    }
}
