// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Basic result with a success/error flag and message.
    /// </summary>
    public partial class ResQYttriumWebApiModelsResultModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsResultModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsResultModel(bool? wasSuccessful = default(bool?), string errorMessage = default(string))
        {
            WasSuccessful = wasSuccessful;
            ErrorMessage = errorMessage;
        }

        /// <summary>
        /// True if the operation was successful, false otherwise with a
        /// message in &lt;see
        /// cref="P:ResQ.Yttrium.WebApi.Models.ResultModel.ErrorMessage"&gt;ErrorMessage&lt;/see&gt;.
        /// </summary>
        [JsonProperty(PropertyName = "WasSuccessful")]
        public bool? WasSuccessful { get; set; }

        /// <summary>
        /// A friendly message indicating what went wrong if there was an
        /// error processing the request.
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; set; }

    }
}
