// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsCalAmpVehicleModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCalAmpVehicleModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCalAmpVehicleModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCalAmpVehicleModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCalAmpVehicleModel(string vin = default(string), string vinRegion = default(string), string make = default(string), string model = default(string), string year = default(string))
        {
            Vin = vin;
            VinRegion = vinRegion;
            Make = make;
            Model = model;
            Year = year;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vin")]
        public string Vin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vin-region")]
        public string VinRegion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "make")]
        public string Make { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public string Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public string Year { get; set; }

    }
}
