// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQNickelZirconiumCommonWebHookDtosLocationWebHookDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosLocationWebHookDto class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosLocationWebHookDto() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosLocationWebHookDto class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosLocationWebHookDto(double? latitude = default(double?), double? longitude = default(double?), string address = default(string), string suburb = default(string), string city = default(string), string province = default(string), string country = default(string))
        {
            Latitude = latitude;
            Longitude = longitude;
            Address = address;
            Suburb = suburb;
            City = city;
            Province = province;
            Country = country;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Suburb")]
        public string Suburb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Province")]
        public string Province { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

    }
}
