// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Input model when adding a service comment.
    /// </summary>
    public partial class ResQYttriumWebApiModelsCreateServiceCommentModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCreateServiceCommentModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCreateServiceCommentModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCreateServiceCommentModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCreateServiceCommentModel(Guid serviceId, string comment, Guid commentorId, DateTime date)
        {
            ServiceId = serviceId;
            Comment = comment;
            CommentorId = commentorId;
            Date = date;
        }

        /// <summary>
        /// Id or the case service to add the comment to.
        /// </summary>
        [JsonProperty(PropertyName = "ServiceId")]
        public Guid ServiceId { get; set; }

        /// <summary>
        /// The comment to add to the service.
        /// </summary>
        [JsonProperty(PropertyName = "Comment")]
        public string Comment { get; set; }

        /// <summary>
        /// User Id of the person who added the comment.
        /// </summary>
        [JsonProperty(PropertyName = "CommentorId")]
        public Guid CommentorId { get; set; }

        /// <summary>
        /// The UTC date of the comment.
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime Date { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Comment == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Comment");
            }
        }
    }
}
