// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsUpdateFinancialDocumentExportModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsUpdateFinancialDocumentExportModel class.
        /// </summary>
        public ResQYttriumWebApiModelsUpdateFinancialDocumentExportModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsUpdateFinancialDocumentExportModel class.
        /// </summary>
        public ResQYttriumWebApiModelsUpdateFinancialDocumentExportModel(Guid? externalFinancialSystemId = default(Guid?), string externalDocumentReference = default(string), string documentStatus = default(string), double? unallocatedAmount = default(double?), double? allocatedAmount = default(double?), IList<ResQYttriumWebApiModelsFinancialDocumentExportAllocationInformation> allocations = default(IList<ResQYttriumWebApiModelsFinancialDocumentExportAllocationInformation>))
        {
            ExternalFinancialSystemId = externalFinancialSystemId;
            ExternalDocumentReference = externalDocumentReference;
            DocumentStatus = documentStatus;
            UnallocatedAmount = unallocatedAmount;
            AllocatedAmount = allocatedAmount;
            Allocations = allocations;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalFinancialSystemId")]
        public Guid? ExternalFinancialSystemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalDocumentReference")]
        public string ExternalDocumentReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DocumentStatus")]
        public string DocumentStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnallocatedAmount")]
        public double? UnallocatedAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AllocatedAmount")]
        public double? AllocatedAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Allocations")]
        public IList<ResQYttriumWebApiModelsFinancialDocumentExportAllocationInformation> Allocations { get; set; }

    }
}
