// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsPaymentSpecificationModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsPaymentSpecificationModel class.
        /// </summary>
        public ResQYttriumWebApiModelsPaymentSpecificationModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsPaymentSpecificationModel class.
        /// </summary>
        public ResQYttriumWebApiModelsPaymentSpecificationModel(string cashPortion = default(string), bool? cash = default(bool?), bool? outOfBenefitBenefit = default(bool?))
        {
            CashPortion = cashPortion;
            Cash = cash;
            OutOfBenefitBenefit = outOfBenefitBenefit;
        }

        /// <summary>
        /// The cash portion amount
        /// </summary>
        [JsonProperty(PropertyName = "CashPortion")]
        public string CashPortion { get; set; }

        /// <summary>
        /// Inidicates that the fee should be payed by the customer
        /// </summary>
        [JsonProperty(PropertyName = "Cash")]
        public bool? Cash { get; set; }

        /// <summary>
        /// Indicates that the customer does not qualify for the service but
        /// the insurer is still willing to cover it.
        /// </summary>
        [JsonProperty(PropertyName = "OutOfBenefitBenefit")]
        public bool? OutOfBenefitBenefit { get; set; }

    }
}
