// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The model that carries the information of comments that was added to a
    /// case.
    /// </summary>
    public partial class ResQYttriumWebApiModelsCaseCommentAddedWebHookModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCaseCommentAddedWebHookModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCaseCommentAddedWebHookModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCaseCommentAddedWebHookModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCaseCommentAddedWebHookModel(Guid? caseId = default(Guid?), string comment = default(string), ResQYttriumWebApiModelsUserWebHookModel user = default(ResQYttriumWebApiModelsUserWebHookModel), Guid? operationId = default(Guid?), DateTime? dateOfOperationTrigger = default(DateTime?))
        {
            CaseId = caseId;
            Comment = comment;
            User = user;
            OperationId = operationId;
            DateOfOperationTrigger = dateOfOperationTrigger;
        }

        /// <summary>
        /// The Dreamtec ID for the case to which the comment was added.
        /// </summary>
        [JsonProperty(PropertyName = "CaseId")]
        public Guid? CaseId { get; set; }

        /// <summary>
        /// The actual comment that was added.
        /// </summary>
        [JsonProperty(PropertyName = "Comment")]
        public string Comment { get; set; }

        /// <summary>
        /// The user that added the comment.
        /// </summary>
        [JsonProperty(PropertyName = "User")]
        public ResQYttriumWebApiModelsUserWebHookModel User { get; set; }

        /// <summary>
        /// This is an ID that identifies the operation. If a operation failed
        /// to push to the webhook
        /// Dreamtec will retry the operation with the exact same operation ID.
        /// </summary>
        [JsonProperty(PropertyName = "OperationId")]
        public Guid? OperationId { get; set; }

        /// <summary>
        /// This is the date that the operation trigger was performed.
        /// </summary>
        [JsonProperty(PropertyName = "DateOfOperationTrigger")]
        public DateTime? DateOfOperationTrigger { get; set; }

    }
}
