// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Basic details of a contact person
    /// </summary>
    public partial class ResQYttriumWebApiModelsContactPersonModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsContactPersonModel class.
        /// </summary>
        public ResQYttriumWebApiModelsContactPersonModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsContactPersonModel class.
        /// </summary>
        public ResQYttriumWebApiModelsContactPersonModel(string firstName = default(string), string surname = default(string), string contactNumber = default(string), string contactEmail = default(string))
        {
            FirstName = firstName;
            Surname = surname;
            ContactNumber = contactNumber;
            ContactEmail = contactEmail;
        }

        /// <summary>
        /// First name(s) of the person.
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// Last name of the person.
        /// </summary>
        [JsonProperty(PropertyName = "Surname")]
        public string Surname { get; set; }

        /// <summary>
        /// Primary telephone number to use when contacting.
        /// </summary>
        [JsonProperty(PropertyName = "ContactNumber")]
        public string ContactNumber { get; set; }

        /// <summary>
        /// Email address to use, e.g. for notifications.
        /// </summary>
        [JsonProperty(PropertyName = "ContactEmail")]
        public string ContactEmail { get; set; }

    }
}
