// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsSauIntegrationIncident
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsSauIntegrationIncident class.
        /// </summary>
        public ResQYttriumWebApiModelsSauIntegrationIncident() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsSauIntegrationIncident class.
        /// </summary>
        public ResQYttriumWebApiModelsSauIntegrationIncident(string action = default(string), string agentName = default(string), string comments = default(string), string contactName = default(string), string contactPhoneNo = default(string), string customerTitle = default(string), string customerFirstName = default(string), string customerIDNo = default(string), string customerLastName = default(string), string customerPhoneNo = default(string), string deliveryAddress = default(string), string deliveryIntersection = default(string), double? deliveryLatitude = default(double?), double? deliveryLongitude = default(double?), string deliveryProvince = default(string), string deliveryStreet = default(string), string deliverySuburb = default(string), string memberNo = default(string), string orderNo = default(string), string pickUpAddress = default(string), string pickUpIntersection = default(string), double? pickUpLatitude = default(double?), double? pickUpLongitude = default(double?), string pickUpProvince = default(string), string pickUpStreet = default(string), string pickUpSuburb = default(string), string vehicleColour = default(string), int? vehicleMMCode = default(int?), int? vehicleProblemID = default(int?), string vehicleRegistration = default(string), string vehicleVIN = default(string), int? vehicleYear = default(int?))
        {
            Action = action;
            AgentName = agentName;
            Comments = comments;
            ContactName = contactName;
            ContactPhoneNo = contactPhoneNo;
            CustomerTitle = customerTitle;
            CustomerFirstName = customerFirstName;
            CustomerIDNo = customerIDNo;
            CustomerLastName = customerLastName;
            CustomerPhoneNo = customerPhoneNo;
            DeliveryAddress = deliveryAddress;
            DeliveryIntersection = deliveryIntersection;
            DeliveryLatitude = deliveryLatitude;
            DeliveryLongitude = deliveryLongitude;
            DeliveryProvince = deliveryProvince;
            DeliveryStreet = deliveryStreet;
            DeliverySuburb = deliverySuburb;
            MemberNo = memberNo;
            OrderNo = orderNo;
            PickUpAddress = pickUpAddress;
            PickUpIntersection = pickUpIntersection;
            PickUpLatitude = pickUpLatitude;
            PickUpLongitude = pickUpLongitude;
            PickUpProvince = pickUpProvince;
            PickUpStreet = pickUpStreet;
            PickUpSuburb = pickUpSuburb;
            VehicleColour = vehicleColour;
            VehicleMMCode = vehicleMMCode;
            VehicleProblemID = vehicleProblemID;
            VehicleRegistration = vehicleRegistration;
            VehicleVIN = vehicleVIN;
            VehicleYear = vehicleYear;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Action")]
        public string Action { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AgentName")]
        public string AgentName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Comments")]
        public string Comments { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactName")]
        public string ContactName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactPhoneNo")]
        public string ContactPhoneNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerTitle")]
        public string CustomerTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerFirstName")]
        public string CustomerFirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerIDNo")]
        public string CustomerIDNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerLastName")]
        public string CustomerLastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerPhoneNo")]
        public string CustomerPhoneNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeliveryAddress")]
        public string DeliveryAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeliveryIntersection")]
        public string DeliveryIntersection { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeliveryLatitude")]
        public double? DeliveryLatitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeliveryLongitude")]
        public double? DeliveryLongitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeliveryProvince")]
        public string DeliveryProvince { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeliveryStreet")]
        public string DeliveryStreet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeliverySuburb")]
        public string DeliverySuburb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MemberNo")]
        public string MemberNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderNo")]
        public string OrderNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PickUpAddress")]
        public string PickUpAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PickUpIntersection")]
        public string PickUpIntersection { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PickUpLatitude")]
        public double? PickUpLatitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PickUpLongitude")]
        public double? PickUpLongitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PickUpProvince")]
        public string PickUpProvince { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PickUpStreet")]
        public string PickUpStreet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PickUpSuburb")]
        public string PickUpSuburb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleColour")]
        public string VehicleColour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleMMCode")]
        public int? VehicleMMCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleProblemID")]
        public int? VehicleProblemID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleRegistration")]
        public string VehicleRegistration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleVIN")]
        public string VehicleVIN { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VehicleYear")]
        public int? VehicleYear { get; set; }

    }
}
