// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQNickelZirconiumCommonWebHookDtosPolicyWebHookDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosPolicyWebHookDto class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosPolicyWebHookDto() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosPolicyWebHookDto class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosPolicyWebHookDto(string companyName = default(string), string firstName = default(string), string surname = default(string), string identityNumber = default(string), DateTime? dateOfBirth = default(DateTime?), string policyNumber = default(string), string contactNumber = default(string))
        {
            CompanyName = companyName;
            FirstName = firstName;
            Surname = surname;
            IdentityNumber = identityNumber;
            DateOfBirth = dateOfBirth;
            PolicyNumber = policyNumber;
            ContactNumber = contactNumber;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CompanyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Surname")]
        public string Surname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IdentityNumber")]
        public string IdentityNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateOfBirth")]
        public DateTime? DateOfBirth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PolicyNumber")]
        public string PolicyNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactNumber")]
        public string ContactNumber { get; set; }

    }
}
