// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsChangeLocationModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsChangeLocationModel class.
        /// </summary>
        public ResQYttriumWebApiModelsChangeLocationModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsChangeLocationModel class.
        /// </summary>
        public ResQYttriumWebApiModelsChangeLocationModel(Guid serviceId, ResQYttriumWebApiModelsLocationModel updatedLocation = default(ResQYttriumWebApiModelsLocationModel))
        {
            ServiceId = serviceId;
            UpdatedLocation = updatedLocation;
        }

        /// <summary>
        /// The service to change the location of.
        /// </summary>
        [JsonProperty(PropertyName = "ServiceId")]
        public Guid ServiceId { get; set; }

        /// <summary>
        /// The new location.
        /// </summary>
        [JsonProperty(PropertyName = "UpdatedLocation")]
        public ResQYttriumWebApiModelsLocationModel UpdatedLocation { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
        }
    }
}
