// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsVehicleModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsVehicleModel class.
        /// </summary>
        public ResQYttriumWebApiModelsVehicleModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsVehicleModel class.
        /// </summary>
        public ResQYttriumWebApiModelsVehicleModel(string licensePlateNumber = default(string), string make = default(string), string model = default(string), string mmCode = default(string), string year = default(string), string color = default(string), string vin = default(string), int? vehicleCode = default(int?), int? writeOffIndicator = default(int?), int? vehicleType = default(int?))
        {
            LicensePlateNumber = licensePlateNumber;
            Make = make;
            Model = model;
            MmCode = mmCode;
            Year = year;
            Color = color;
            Vin = vin;
            VehicleCode = vehicleCode;
            WriteOffIndicator = writeOffIndicator;
            VehicleType = vehicleType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LicensePlateNumber")]
        public string LicensePlateNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Make")]
        public string Make { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Model")]
        public string Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MmCode")]
        public string MmCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public string Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Color")]
        public string Color { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Vin")]
        public string Vin { get; set; }

        /// <summary>
        /// Indicate the condition of the vehicle, e.g. New, Used, etc.
        /// </summary>
        [JsonProperty(PropertyName = "VehicleCode")]
        public int? VehicleCode { get; set; }

        /// <summary>
        /// Indicate the write-off state of the vehicle.
        /// </summary>
        [JsonProperty(PropertyName = "WriteOffIndicator")]
        public int? WriteOffIndicator { get; set; }

        /// <summary>
        /// Indicate the type of vehicle.
        /// </summary>
        [JsonProperty(PropertyName = "VehicleType")]
        public int? VehicleType { get; set; }

    }
}
