// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsSauIntegrationSauRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsSauIntegrationSauRequestModel class.
        /// </summary>
        public ResQYttriumWebApiModelsSauIntegrationSauRequestModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsSauIntegrationSauRequestModel class.
        /// </summary>
        public ResQYttriumWebApiModelsSauIntegrationSauRequestModel(ResQYttriumWebApiModelsSauIntegrationIncident incident = default(ResQYttriumWebApiModelsSauIntegrationIncident), Guid? requestId = default(Guid?))
        {
            Incident = incident;
            RequestId = requestId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Incident")]
        public ResQYttriumWebApiModelsSauIntegrationIncident Incident { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequestId")]
        public Guid? RequestId { get; set; }

    }
}
