// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsSauIntegrationSauRequestResultModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsSauIntegrationSauRequestResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsSauIntegrationSauRequestResultModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsSauIntegrationSauRequestResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsSauIntegrationSauRequestResultModel(bool? wasSuccessful = default(bool?), string reference = default(string), string errorMessage = default(string))
        {
            WasSuccessful = wasSuccessful;
            Reference = reference;
            ErrorMessage = errorMessage;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WasSuccessful")]
        public bool? WasSuccessful { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Reference")]
        public string Reference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; set; }

    }
}
