// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Data required to initiate the automatic dispatch of the service.
    /// </summary>
    public partial class ResQYttriumWebApiModelsInitiateAutoDispatchModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsInitiateAutoDispatchModel class.
        /// </summary>
        public ResQYttriumWebApiModelsInitiateAutoDispatchModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsInitiateAutoDispatchModel class.
        /// </summary>
        public ResQYttriumWebApiModelsInitiateAutoDispatchModel(Guid serviceId)
        {
            ServiceId = serviceId;
        }

        /// <summary>
        /// The id of the service to dispatch.
        /// </summary>
        [JsonProperty(PropertyName = "ServiceId")]
        public Guid ServiceId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
