// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsBulkClientCsiModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsBulkClientCsiModel class.
        /// </summary>
        public ResQYttriumWebApiModelsBulkClientCsiModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsBulkClientCsiModel class.
        /// </summary>
        public ResQYttriumWebApiModelsBulkClientCsiModel(Guid? requestId = default(Guid?), IList<ResQYttriumWebApiModelsClientCsiResponse> clientCsiResponses = default(IList<ResQYttriumWebApiModelsClientCsiResponse>))
        {
            RequestId = requestId;
            ClientCsiResponses = clientCsiResponses;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequestId")]
        public Guid? RequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientCsiResponses")]
        public IList<ResQYttriumWebApiModelsClientCsiResponse> ClientCsiResponses { get; set; }

    }
}
