// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsSignInResultModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsSignInResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsSignInResultModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsSignInResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsSignInResultModel(string accessToken = default(string), string error = default(string), SystemNullableResQBerylliumWebIso8601SerializableDateTimeOffset tokenExpiry = default(SystemNullableResQBerylliumWebIso8601SerializableDateTimeOffset))
        {
            AccessToken = accessToken;
            Error = error;
            TokenExpiry = tokenExpiry;
        }

        /// <summary>
        /// An access token that can be used to access the requested
        /// application resource
        /// </summary>
        [JsonProperty(PropertyName = "AccessToken")]
        public string AccessToken { get; set; }

        /// <summary>
        /// This field is populated when the request for an access token has
        /// failed with the reason for the failure
        /// </summary>
        [JsonProperty(PropertyName = "Error")]
        public string Error { get; set; }

        /// <summary>
        /// The datetime until which the access token is valid and can be used
        /// to access the requested application resource
        /// </summary>
        [JsonProperty(PropertyName = "TokenExpiry")]
        public SystemNullableResQBerylliumWebIso8601SerializableDateTimeOffset TokenExpiry { get; set; }

    }
}
