// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsCreateUserResultModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCreateUserResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCreateUserResultModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCreateUserResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCreateUserResultModel(Guid? userId = default(Guid?), string error = default(string))
        {
            UserId = userId;
            Error = error;
        }

        /// <summary>
        /// The id of the user to be used during the sign-in user process.
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public Guid? UserId { get; set; }

        /// <summary>
        /// This field is populated when the request to create a user has
        /// failed with the reason for the failure
        /// </summary>
        [JsonProperty(PropertyName = "Error")]
        public string Error { get; set; }

    }
}
