// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQNickelZirconiumCommonWebHookDtosServiceProviderAssignmentWebHookDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosServiceProviderAssignmentWebHookDto
        /// class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosServiceProviderAssignmentWebHookDto() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosServiceProviderAssignmentWebHookDto
        /// class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosServiceProviderAssignmentWebHookDto(string authorizationReference = default(string), DateTime? dateAssigned = default(DateTime?), ResQNickelZirconiumCommonWebHookDtosLocationWebHookDto dispatchLocation = default(ResQNickelZirconiumCommonWebHookDtosLocationWebHookDto), double? kilometersToIncidentByRoad = default(double?), ResQNickelZirconiumCommonWebHookDtosRepresentativeWebHookDto representative = default(ResQNickelZirconiumCommonWebHookDtosRepresentativeWebHookDto), string representativePhotoUrl = default(string), Guid? physicalDevicePersonLinkId = default(Guid?))
        {
            AuthorizationReference = authorizationReference;
            DateAssigned = dateAssigned;
            DispatchLocation = dispatchLocation;
            KilometersToIncidentByRoad = kilometersToIncidentByRoad;
            Representative = representative;
            RepresentativePhotoUrl = representativePhotoUrl;
            PhysicalDevicePersonLinkId = physicalDevicePersonLinkId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AuthorizationReference")]
        public string AuthorizationReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateAssigned")]
        public DateTime? DateAssigned { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DispatchLocation")]
        public ResQNickelZirconiumCommonWebHookDtosLocationWebHookDto DispatchLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KilometersToIncidentByRoad")]
        public double? KilometersToIncidentByRoad { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Representative")]
        public ResQNickelZirconiumCommonWebHookDtosRepresentativeWebHookDto Representative { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RepresentativePhotoUrl")]
        public string RepresentativePhotoUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PhysicalDevicePersonLinkId")]
        public Guid? PhysicalDevicePersonLinkId { get; set; }

    }
}
