// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsCreateUserModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCreateUserModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCreateUserModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCreateUserModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCreateUserModel(Guid clientId, Guid operationsNodeId, string emailAddress = default(string), string uniqueReferenceNumber = default(string), string firstName = default(string), string surname = default(string))
        {
            ClientId = clientId;
            EmailAddress = emailAddress;
            UniqueReferenceNumber = uniqueReferenceNumber;
            FirstName = firstName;
            Surname = surname;
            OperationsNodeId = operationsNodeId;
        }

        /// <summary>
        /// The id of the client that is requesting to create the user.
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public Guid ClientId { get; set; }

        /// <summary>
        /// The email address of the user.
        /// </summary>
        [JsonProperty(PropertyName = "EmailAddress")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// The unique reference of the user.
        /// </summary>
        [JsonProperty(PropertyName = "UniqueReferenceNumber")]
        public string UniqueReferenceNumber { get; set; }

        /// <summary>
        /// The first name of the user.
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// The surname of the user.
        /// </summary>
        [JsonProperty(PropertyName = "Surname")]
        public string Surname { get; set; }

        /// <summary>
        /// The id of the operations center that is creating the user.
        /// </summary>
        [JsonProperty(PropertyName = "OperationsNodeId")]
        public Guid OperationsNodeId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
