// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Data required to schedule a service.
    /// </summary>
    public partial class ResQYttriumWebApiModelsRescheduleServiceModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsRescheduleServiceModel class.
        /// </summary>
        public ResQYttriumWebApiModelsRescheduleServiceModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsRescheduleServiceModel class.
        /// </summary>
        public ResQYttriumWebApiModelsRescheduleServiceModel(Guid serviceId, ResQYttriumWebApiModelsScheduleModel scheduleInfo)
        {
            ServiceId = serviceId;
            ScheduleInfo = scheduleInfo;
        }

        /// <summary>
        /// The id of the service to reschedule.
        /// </summary>
        [JsonProperty(PropertyName = "ServiceId")]
        public Guid ServiceId { get; set; }

        /// <summary>
        /// The schedule info for the service.
        /// </summary>
        [JsonProperty(PropertyName = "ScheduleInfo")]
        public ResQYttriumWebApiModelsScheduleModel ScheduleInfo { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ScheduleInfo == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ScheduleInfo");
            }
        }
    }
}
