// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Response DTO of the created Accident Tow Service.
    /// </summary>
    public partial class ResQYttriumWebApiModelsCreateAccidentTowServiceResultModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCreateAccidentTowServiceResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCreateAccidentTowServiceResultModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsCreateAccidentTowServiceResultModel class.
        /// </summary>
        public ResQYttriumWebApiModelsCreateAccidentTowServiceResultModel(string reference = default(string), Guid? serviceId = default(Guid?), bool? wasSuccessful = default(bool?), string errorMessage = default(string))
        {
            Reference = reference;
            ServiceId = serviceId;
            WasSuccessful = wasSuccessful;
            ErrorMessage = errorMessage;
        }

        /// <summary>
        /// The Reference of the case service that was created.  This is not
        /// yet being populated, but will be soon.  It will likely be moved
        /// up to CreateServiceResultModel.
        /// </summary>
        [JsonProperty(PropertyName = "Reference")]
        public string Reference { get; set; }

        /// <summary>
        /// The id of the service that was created.
        /// </summary>
        [JsonProperty(PropertyName = "ServiceId")]
        public Guid? ServiceId { get; set; }

        /// <summary>
        /// True if the operation was successful, false otherwise with a
        /// message in &lt;see
        /// cref="P:ResQ.Yttrium.WebApi.Models.ResultModel.ErrorMessage"&gt;ErrorMessage&lt;/see&gt;.
        /// </summary>
        [JsonProperty(PropertyName = "WasSuccessful")]
        public bool? WasSuccessful { get; set; }

        /// <summary>
        /// A friendly message indicating what went wrong if there was an
        /// error processing the request.
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; set; }

    }
}
