// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsLocationModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsLocationModel class.
        /// </summary>
        public ResQYttriumWebApiModelsLocationModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsLocationModel class.
        /// </summary>
        public ResQYttriumWebApiModelsLocationModel(string extraLocationInformation = default(string), double? lat = default(double?), double? lon = default(double?))
        {
            ExtraLocationInformation = extraLocationInformation;
            Lat = lat;
            Lon = lon;
        }

        /// <summary>
        /// Extra information of the location, including the full text address
        /// and unit number if applicable.
        /// </summary>
        [JsonProperty(PropertyName = "ExtraLocationInformation")]
        public string ExtraLocationInformation { get; set; }

        /// <summary>
        /// The Latitude of the location.
        /// </summary>
        [JsonProperty(PropertyName = "Lat")]
        public double? Lat { get; set; }

        /// <summary>
        /// The Longitude of the location.
        /// </summary>
        [JsonProperty(PropertyName = "Lon")]
        public double? Lon { get; set; }

    }
}
