// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQNickelZirconiumCommonWebHookDtosCaseCreatedWebHookModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosCaseCreatedWebHookModel class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosCaseCreatedWebHookModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosCaseCreatedWebHookModel class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosCaseCreatedWebHookModel(Guid? id = default(Guid?), DateTime? dateCreated = default(DateTime?), DateTime? dateOfIncident = default(DateTime?), IList<string> references = default(IList<string>), string externalReference = default(string), ResQNickelZirconiumCommonWebHookDtosKeyValuePairWebHookDto caseClassification = default(ResQNickelZirconiumCommonWebHookDtosKeyValuePairWebHookDto), ResQNickelZirconiumCommonWebHookDtosKeyValuePairWebHookDto masterState = default(ResQNickelZirconiumCommonWebHookDtosKeyValuePairWebHookDto), ResQNickelZirconiumCommonWebHookDtosContactPersonWebHookDto contactPerson = default(ResQNickelZirconiumCommonWebHookDtosContactPersonWebHookDto), ResQNickelZirconiumCommonWebHookDtosVehicleWebHookDto vehicle = default(ResQNickelZirconiumCommonWebHookDtosVehicleWebHookDto), ResQNickelZirconiumCommonWebHookDtosPolicyWebHookDto policy = default(ResQNickelZirconiumCommonWebHookDtosPolicyWebHookDto), ResQNickelZirconiumCommonWebHookDtosRelationshipWebHookDto client = default(ResQNickelZirconiumCommonWebHookDtosRelationshipWebHookDto), ResQNickelZirconiumCommonWebHookDtosRelationshipWebHookDto customerLiaison = default(ResQNickelZirconiumCommonWebHookDtosRelationshipWebHookDto), Guid? operationId = default(Guid?), DateTime? dateOfOperationTrigger = default(DateTime?))
        {
            Id = id;
            DateCreated = dateCreated;
            DateOfIncident = dateOfIncident;
            References = references;
            ExternalReference = externalReference;
            CaseClassification = caseClassification;
            MasterState = masterState;
            ContactPerson = contactPerson;
            Vehicle = vehicle;
            Policy = policy;
            Client = client;
            CustomerLiaison = customerLiaison;
            OperationId = operationId;
            DateOfOperationTrigger = dateOfOperationTrigger;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCreated")]
        public DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateOfIncident")]
        public DateTime? DateOfIncident { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "References")]
        public IList<string> References { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalReference")]
        public string ExternalReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CaseClassification")]
        public ResQNickelZirconiumCommonWebHookDtosKeyValuePairWebHookDto CaseClassification { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MasterState")]
        public ResQNickelZirconiumCommonWebHookDtosKeyValuePairWebHookDto MasterState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactPerson")]
        public ResQNickelZirconiumCommonWebHookDtosContactPersonWebHookDto ContactPerson { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Vehicle")]
        public ResQNickelZirconiumCommonWebHookDtosVehicleWebHookDto Vehicle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Policy")]
        public ResQNickelZirconiumCommonWebHookDtosPolicyWebHookDto Policy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Client")]
        public ResQNickelZirconiumCommonWebHookDtosRelationshipWebHookDto Client { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerLiaison")]
        public ResQNickelZirconiumCommonWebHookDtosRelationshipWebHookDto CustomerLiaison { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperationId")]
        public Guid? OperationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateOfOperationTrigger")]
        public DateTime? DateOfOperationTrigger { get; set; }

    }
}
