// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsFinancialDocumentExportAllocationInformation
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsFinancialDocumentExportAllocationInformation
        /// class.
        /// </summary>
        public ResQYttriumWebApiModelsFinancialDocumentExportAllocationInformation() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsFinancialDocumentExportAllocationInformation
        /// class.
        /// </summary>
        public ResQYttriumWebApiModelsFinancialDocumentExportAllocationInformation(double? amount = default(double?), string fromDocumentReference = default(string), string byUser = default(string), DateTime? utcTimestamp = default(DateTime?))
        {
            Amount = amount;
            FromDocumentReference = fromDocumentReference;
            ByUser = byUser;
            UtcTimestamp = utcTimestamp;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromDocumentReference")]
        public string FromDocumentReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ByUser")]
        public string ByUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UtcTimestamp")]
        public DateTime? UtcTimestamp { get; set; }

    }
}
