// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQNickelZirconiumCommonWebHookDtosContactPersonWebHookDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosContactPersonWebHookDto class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosContactPersonWebHookDto() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQNickelZirconiumCommonWebHookDtosContactPersonWebHookDto class.
        /// </summary>
        public ResQNickelZirconiumCommonWebHookDtosContactPersonWebHookDto(string firstName = default(string), string surname = default(string), string contactNumber = default(string), string alternativeContactNumber = default(string), string emailAddress = default(string))
        {
            FirstName = firstName;
            Surname = surname;
            ContactNumber = contactNumber;
            AlternativeContactNumber = alternativeContactNumber;
            EmailAddress = emailAddress;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Surname")]
        public string Surname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactNumber")]
        public string ContactNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AlternativeContactNumber")]
        public string AlternativeContactNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmailAddress")]
        public string EmailAddress { get; set; }

    }
}
