// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResQYttriumWebApiModelsTrackerIntegrationVehicle
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsTrackerIntegrationVehicle class.
        /// </summary>
        public ResQYttriumWebApiModelsTrackerIntegrationVehicle() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ResQYttriumWebApiModelsTrackerIntegrationVehicle class.
        /// </summary>
        public ResQYttriumWebApiModelsTrackerIntegrationVehicle(string registrationNumber = default(string), string vINNumber = default(string), string colour = default(string), string make = default(string), string model = default(string), int? year = default(int?), int? oDOReading = default(int?))
        {
            RegistrationNumber = registrationNumber;
            VINNumber = vINNumber;
            Colour = colour;
            Make = make;
            Model = model;
            Year = year;
            ODOReading = oDOReading;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegistrationNumber")]
        public string RegistrationNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VINNumber")]
        public string VINNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Colour")]
        public string Colour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Make")]
        public string Make { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Model")]
        public string Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ODOReading")]
        public int? ODOReading { get; set; }

    }
}
