// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for AccidentTowService.
    /// </summary>
    public static partial class AccidentTowServiceExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static ResQYttriumWebApiModelsCreateAccidentTowServiceResultModel Create(this IAccidentTowService operations, ResQYttriumWebApiModelsCreateAccidentTowServiceModel model)
            {
                return Task.Factory.StartNew(s => ((IAccidentTowService)s).CreateAsync(model), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ResQYttriumWebApiModelsCreateAccidentTowServiceResultModel> CreateAsync(this IAccidentTowService operations, ResQYttriumWebApiModelsCreateAccidentTowServiceModel model, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static ResQYttriumWebApiModelsResultModel ChangeDestination(this IAccidentTowService operations, ResQYttriumWebApiModelsChangeLocationModel model)
            {
                return Task.Factory.StartNew(s => ((IAccidentTowService)s).ChangeDestinationAsync(model), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ResQYttriumWebApiModelsResultModel> ChangeDestinationAsync(this IAccidentTowService operations, ResQYttriumWebApiModelsChangeLocationModel model, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ChangeDestinationWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
