// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for CalAmp.
    /// </summary>
    public static partial class CalAmpExtensions
    {
            /// <summary>
            /// This request can be used for CalAmp integration.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static void CalAmpNotification(this ICalAmp operations, ResQYttriumWebApiModelsCalAmpNotificationModel model)
            {
                Task.Factory.StartNew(s => ((ICalAmp)s).CalAmpNotificationAsync(model), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// This request can be used for CalAmp integration.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task CalAmpNotificationAsync(this ICalAmp operations, ResQYttriumWebApiModelsCalAmpNotificationModel model, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.CalAmpNotificationWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
