// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Service operations.
    /// </summary>
    public partial interface IService
    {
        /// <summary>
        /// Logs a user comment on a Case Service.
        /// </summary>
        /// <param name='model'>
        /// Model identifying the case service and containing the comment
        /// detail.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ResQYttriumWebApiModelsResultModel>> AddCommentWithHttpMessagesAsync(ResQYttriumWebApiModelsCreateServiceCommentModel model, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Requests cancellation of the case service.
        /// </summary>
        /// <param name='model'>
        /// Model identifying the service to cancel.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ResQYttriumWebApiModelsResultModel>> CancelServiceWithHttpMessagesAsync(ResQYttriumWebApiModelsCancelServiceModel model, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Provide new schedule information for a case service.
        /// </summary>
        /// <param name='model'>
        /// Model identifying the case service to reshcedule as well as the
        /// schedule detail.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ResQYttriumWebApiModelsResultModel>> RescheduleServiceWithHttpMessagesAsync(ResQYttriumWebApiModelsRescheduleServiceModel model, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Update the tag(s) of a case service.
        /// Only one group's tags can be set per invocation of this method.
        /// Use multiple calls to update different tag groups.
        /// </summary>
        /// <param name='model'>
        /// Model identifying the case service to update and the list of tags
        /// to apply for a specific tag group.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ResQYttriumWebApiModelsResultModel>> UpdateTagWithHttpMessagesAsync(ResQYttriumWebApiModelsUpdateCaseServiceTagModel model, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Triggers the automatic dispatch of a service.
        /// </summary>
        /// <param name='model'>
        /// Model identifying the case service to dispatch.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ResQYttriumWebApiModelsResultModel>> InitiateAutoDispatchWithHttpMessagesAsync(ResQYttriumWebApiModelsInitiateAutoDispatchModel model, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Submit a rating by a customer or relevant party about a service
        /// that was rendered.
        /// </summary>
        /// <param name='model'>
        /// Model identifying the case service and providing the rating detail.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ResQYttriumWebApiModelsSubmitCaseServiceRatingResultModel>> SubmitRatingWithHttpMessagesAsync(ResQYttriumWebApiModelsSubmitRatingModel model, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
