// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for SauIntegration.
    /// </summary>
    public static partial class SauIntegrationExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static bool? Trigger(this ISauIntegration operations, ResQYttriumWebApiControllersSauIntegrationControllerIntegrateSauDto model)
            {
                return Task.Factory.StartNew(s => ((ISauIntegration)s).TriggerAsync(model), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<bool?> TriggerAsync(this ISauIntegration operations, ResQYttriumWebApiControllersSauIntegrationControllerIntegrateSauDto model, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.TriggerWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static ResQYttriumWebApiModelsSauIntegrationSauRequestResultModel SubmitIncident(this ISauIntegration operations, ResQYttriumWebApiModelsSauIntegrationSauRequestModel model)
            {
                return Task.Factory.StartNew(s => ((ISauIntegration)s).SubmitIncidentAsync(model), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ResQYttriumWebApiModelsSauIntegrationSauRequestResultModel> SubmitIncidentAsync(this ISauIntegration operations, ResQYttriumWebApiModelsSauIntegrationSauRequestModel model, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SubmitIncidentWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
