// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DreamtecSyncJob.Yttrium
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for TradeTowService.
    /// </summary>
    public static partial class TradeTowServiceExtensions
    {
            /// <summary>
            /// Creates a new Trade Tow / Upliftment Tow service.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// Data model for creating the service.
            /// </param>
            public static ResQYttriumWebApiModelsCreateTradeTowServiceResultModel Create(this ITradeTowService operations, ResQYttriumWebApiModelsCreateTradeTowServiceModel model)
            {
                return Task.Factory.StartNew(s => ((ITradeTowService)s).CreateAsync(model), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates a new Trade Tow / Upliftment Tow service.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// Data model for creating the service.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ResQYttriumWebApiModelsCreateTradeTowServiceResultModel> CreateAsync(this ITradeTowService operations, ResQYttriumWebApiModelsCreateTradeTowServiceModel model, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
